
image: macos

environment:
    R_VERSION: 3.6.1
    MACOSX_DEPLOYMENT_TARGET: 10.11
    CRAN_MIRROR: https://cran.microsoft.com/snapshot/2020-01-01
    FC: /usr/local/gfortran/bin/gfortran

install:
  - curl -o clang.pkg https://cloud.r-project.org/bin/macosx/tools/clang-7.0.0.pkg
  - sudo installer -pkg clang.pkg -target /
  - curl -o gfortran.pkg https://cloud.r-project.org/bin/macosx/tools/gfortran-6.1.pkg
  - sudo installer -pkg gfortran.pkg -target /
  - curl -o XQuartz.pkg https://www.jamovi.org/misc/XQuartz.pkg
  - sudo installer -package XQuartz.pkg -target /
  - curl https://cloud.r-project.org/src/base/R-3/R-$R_VERSION.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/pcre-8.40-darwin.15-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/pixman-0.32.6-darwin.13-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/fontconfig-2.11.1-darwin.13-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/freetype-2.5.5-darwin.13-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/cairo-1.14.2-darwin.13-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/libpng-1.6.28-darwin.15-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/jpeg-9-darwin.15-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/tiff-4.0.7-darwin.15-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/readline-5.2-12-darwin8-bin4.tar.gz | tar xz
  - sudo ditto usr/local /usr/local

build_script:

  - export PATH="/usr/local/clang7/bin:$PATH"
  - cd R-$R_VERSION
  
  # - cat configure | grep -v "#include <cairo-xlib.h>" >tmp
  # - cat tmp >configure
  # - rm tmp
  
  - ./configure  'CC=clang' 'CXX=clang++' 'OBJC=clang' 'CFLAGS=-Wall -g -O2' 'CPPFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include' 'CXXFLAGS=-Wall -g -O2' 'OBJCFLAGS=-Wall -g -O2' 'FCFLAGS=-Wall -g -O2' 'F77FLAGS=-Wall -g -O2' '--enable-memory-profiling' '--x-libraries=/opt/X11/lib' '--enable-R-framework' 'PKG_CONFIG_PATH=/usr/lib/pkgconfig:/opt/X11/lib/pkgconfig:/usr/local/lib/pkgconfig' || true
  - make

artifacts:
  - name: Logs
    path: "R-$R_VERSION/*.log"
